# Generated by Django 5.1 on 2024-08-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
